### ISSUE TITLE
Implement global RFID input listener

### ISSUE THREAD

**Issue by FredrikAugust** [appKom/nibble95#2]
You have to select the input field before scanning your student card to log in. This is not very intuitive.

**Comment by kharann** [comment]
this ^^^^

**Comment by Paalar** [comment]
Is there any other way to do this besides setting an interval that focuses the input element?

**Comment by FredrikAugust** [comment]
A global "onKeyDown" listener. When you register input, either put it into a buffer, and clean it by debouncing key inputs (if no enter press (key=13) after 200ms, clear input) or focus the input field and enter it there.
