### ISSUE TITLE
Sign out button

### ISSUE THREAD

**Issue by FredrikAugust** [appKom/nibble95#5]
There's no sign out button currently, which is something that is handy to have when checking your balance.

**Comment by Paalar** [comment]
It is, but it is 'hidden'. The exit button on the Store screen logs out the user.

**Comment by FredrikAugust** [comment]
Ah, think we should have a more intuitive way of signing out

**Comment by Paalar** [comment]
Could just change the value to be 'Logout' Or something. Even though it is not true windows95 style.

**Comment by FredrikAugust** [comment]
Do we need "Refresh window"? If not, could just replace that, or add another button next to it that signs you out.
