### ISSUE TITLE
Disable the "Purchase" button when you're not signed in

### ISSUE THREAD

**Issue by FredrikAugust** [appKom/nibble95#7]
When the user is not signed in, the Purchase button should be disabled. Seems strange that you should be able to purchase stuff when you're not signed in.

Proposed implementation;

When the user is signed out, minimise the shop window, so that it is accessible by clicking the taskbar, but hidden by default. Then when they sign in, minimise the login window, and maximise the shop window.

This would also solve #4, as you could have both be floating window without interfering with one-another.

**Comment by Paalar** [comment]
In my opinion I think the user should be able to view all the items, even when not logged in. Having another window hovering above the shop window would hide several items. I also believe that the login scanner should be above everything, as it is imperative for user interaction. I believe that user interaction should be more important that win95 authenticity.
